/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.hb.store;

public final class Manifest {
    public static final class permission {
        /**  <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" /> 

      IMPORTANT: Change "com.parse.tutorials.pushnotifications.permission.C2D_MESSAGE" in the lines below
      to match your app's package name + ".permission.C2D_MESSAGE".
    
         */
        public static final String C2D_MESSAGE="com.parse.tutorials.pushnotifications.permission.C2D_MESSAGE";
    }
}
